apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-qmserver-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qm.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: qm-project
data:
  APP_NAME: {{ .Values.qmserver.config.appName | quote }}
  PORT: {{ .Values.qmserver.config.port | quote }}
  GIN_MODE: {{ .Values.qmserver.config.ginMode | quote }}
  {{- if .Values.qmserver.billingCheckUrl }}
  QMSERVER_BILLING_CHECK_URL: {{ .Values.qmserver.billingCheckUrl | quote }}
  {{- end }}
