apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-qmserver-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qm.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: qm-project
data:
  APP_NAME: {{ .Values.qmserver.config.appName | quote }}
  QMNETWORK_ISSUER: {{ .Values.qmserver.config.qmnetworkIssuer | quote }}
  PORT: {{ .Values.qmserver.config.port | quote }}
  GIN_MODE: {{ .Values.qmserver.config.ginMode | quote }}
  {{- $jwksScheme := "http" }}
  {{- if .Values.ingress.tls.enabled }}
  {{- $jwksScheme = "https" }}
  {{- end }}
  QMNETWORK_JWKS_URL: {{ printf "%s://%s/.well-known/jwks.json" $jwksScheme .Values.ingress.hosts.auth | quote }}
  QMNETWORK_INTERNAL_URL: {{ .Values.qmserver.config.qmnetworkInternalUrl | default "http://qmnetwork:8080" | quote }}
  {{- if .Values.qmsecret.enabled }}
  QMSECRET_BASE_URL: {{ printf "http://qmsecret:%v" (.Values.qmsecret.port | default 9088) | quote }}
  QMSECRET_PATH_QMNETWORK_INTERNAL: {{ .Values.qmsecret.pathQmnetworkInternal | default "qmserver/qmnetwork/internal_secret" | quote }}
  {{- end }}
