{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: qm-monitoring-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qm.labels" . | nindent 4 }}
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: qm-project
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.monitoring.prometheus.scrapeInterval | quote }}
      evaluation_interval: 30s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: mysqld
        static_configs:
          - targets: ["qm-mysql-exporter:9104"]
      - job_name: blackbox-qmserver-health
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
              - http://qmserver:8080/health
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - target_label: __address__
            replacement: qm-blackbox-exporter:9115
          - source_labels: [__param_target]
            target_label: instance
{{- end }}
