{{- if .Values.persistence.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qmserver-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qm.labels" . | nindent 4 }}
    app.kubernetes.io/part-of: qm-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.qmserver.pvc.storage | quote }}
{{- end }}
