{{- if .Values.qmsecret.enabled }}
{{- if .Values.qmsecret.persistence.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qmsecret-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qm.labels" . | nindent 4 }}
    app.kubernetes.io/name: qmsecret
    app.kubernetes.io/part-of: qm-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.qmsecret.persistence.storage | quote }}
{{- end }}
{{- end }}
