{{- if .Values.smtpRelay.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: smtp-relay-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qm.labels" . | nindent 4 }}
    app.kubernetes.io/name: smtp-relay
    app.kubernetes.io/part-of: qm-project
type: Opaque
stringData:
  SMTP_RELAY_USERS: {{ include "qm.smtpRelayUsersLine" . | quote }}
  QMNETWORK_SMTP_PASSWORD: {{ include "qm.smtpRelayPasswordPlain" . | quote }}
{{- end }}
